client_config_backend: settings
client_config:
  client_id: 376045711788-n233584guq4jf14mp8244fujfeoeo96g.apps.googleusercontent.com
  client_secret: 44tyNFNn7lZvRGfvvlx-v3pG

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install